#!/usr/bin/env python3
"""Stage the static website with copies of its permitted sound previews.

No framework, network access, source media, or signing material is needed.
Existing output can be replaced only if it was created by this script.
"""

import argparse
import json
import re
from pathlib import Path, PurePosixPath
import shutil
import tempfile


ROOT = Path(__file__).resolve().parents[1]
WEBSITE = ROOT / "website"
ASSETS = ROOT / "Assets"
MARKER = ".clicky-website-build"
MARKER_CONTENT = "Generated by Clicky scripts/prepare_website.py\n"
WEBSITE_SUFFIXES = {
    ".html", ".css", ".js", ".svg", ".png", ".webp", ".jpg", ".jpeg",
    ".ico", ".json", ".txt", ".xml", ".woff", ".woff2",
}


def is_within(path, directory):
    return path == directory or directory in path.parents


def validate_output(output):
    if output.is_symlink():
        raise ValueError("The output directory must not be a symbolic link")
    output = output.resolve()
    if is_within(ROOT, output):
        raise ValueError("The output must not be the repository or one of its parents")
    for source in (WEBSITE, ASSETS, ROOT / "scripts", ROOT / "App", ROOT / "Packages", ROOT / ".git"):
        source = source.resolve()
        if is_within(output, source) or is_within(source, output):
            raise ValueError(f"The output must not overlap source directory {source.name}")
    if output.exists():
        marker = output / MARKER
        if (not output.is_dir() or marker.is_symlink() or not marker.is_file()
                or marker.read_text() != MARKER_CONTENT):
            raise ValueError("Refusing to replace a directory not created by this script; choose a new output path")
    return output


def website_files():
    if WEBSITE.is_symlink() or not WEBSITE.is_dir():
        raise ValueError("The website source must be a real directory in this repository")
    files = []
    for path in sorted(WEBSITE.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"Website symbolic links are not published: {path.relative_to(ROOT)}")
        if not path.is_file():
            continue
        relative = path.relative_to(WEBSITE)
        if path.name == ".DS_Store":
            continue
        if path.name != ".nojekyll" and (
                any(part.startswith(".") for part in relative.parts)
                or path.suffix.lower() not in WEBSITE_SUFFIXES):
            raise ValueError(f"Unexpected website file: {relative}")
        if relative.parts[0] in {"sounds", "licenses"} or relative.as_posix() in {"profiles.json", "mouse-profiles.json"}:
            raise ValueError(f"{relative} is reserved for generated sound previews")
        files.append((path, relative))
    for required in ("index.html", "app.js", "config.js", "styles.css"):
        if not any(relative.as_posix() == required for _, relative in files):
            raise ValueError(f"Missing website/{required}")
    return files


def sound_files(manifest="profiles.json"):
    profiles = json.loads((ASSETS / manifest).read_text())
    if not isinstance(profiles, list) or not profiles:
        raise ValueError("Expected a nonempty sound profile catalog")
    ids = [profile["id"] for profile in profiles]
    if (len(set(ids)) != len(ids)
            or any(not isinstance(value, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", value)
                   for value in ids)):
        raise ValueError("Sound profile IDs must be unique lowercase names")
    files = {}
    for profile in profiles:
        def rewrite_bank(bank):
            for field in ("samples", "releaseSamples"):
                entries = bank.get(field)
                if field == "samples" and (not isinstance(entries, list) or not entries):
                    raise ValueError(f"Profile {profile['id']} has an empty sound bank")
                if entries is None:
                    continue
                if not isinstance(entries, list):
                    raise ValueError(f"Profile {profile['id']} has an invalid {field} list")
                rewritten = []
                for entry in entries:
                    relative = PurePosixPath(entry)
                    if (len(relative.parts) < 3 or relative.parts[0] != "Sounds"
                            or relative.parts[1] != profile["id"]
                            or relative.suffix.lower() != ".wav"
                            or ".." in relative.parts or relative.as_posix() != entry):
                        raise ValueError(f"Unexpected sound path: {entry}")
                    source = ASSETS.joinpath(*relative.parts)
                    if (not source.is_file() or source.is_symlink()
                            or any(parent.is_symlink() for parent in source.parents if is_within(parent, ASSETS))
                            or not is_within(source.resolve(), ASSETS.resolve())):
                        raise ValueError(f"Missing or linked sound asset: {entry}")
                    target = Path("sounds", *relative.parts[1:])
                    files[target] = source
                    rewritten.append(target.as_posix())
                bank[field] = rewritten

        rewrite_bank(profile)
        key_samples = profile.get("keySamples")
        if key_samples is not None:
            if not isinstance(key_samples, dict):
                raise ValueError(f"Profile {profile['id']} has invalid key samples")
            for usage, bank in key_samples.items():
                if not re.fullmatch(r"[0-9]+:[0-9]+", usage) or not isinstance(bank, dict):
                    raise ValueError(f"Profile {profile['id']} has an invalid key sound bank")
                rewrite_bank(bank)
    return profiles, [(source, target) for target, source in files.items()]


def license_files():
    files = []
    for name in ("kbsim-MIT.txt", "Sadiquecat-CC0.txt"):
        source = ASSETS / "Licenses" / name
        if (not source.is_file() or source.is_symlink()
                or any(parent.is_symlink() for parent in source.parents if is_within(parent, ASSETS))
                or not is_within(source.resolve(), ASSETS.resolve())):
            raise ValueError(f"Missing or linked sound license: Licenses/{name}")
        files.append((source, Path("licenses", name)))
    return files


def mouse_sound_files():
    source = ASSETS / "Sounds" / "Extras" / "soft.wav"
    if (not source.is_file() or source.is_symlink()
            or any(parent.is_symlink() for parent in source.parents if is_within(parent, ASSETS))
            or not is_within(source.resolve(), ASSETS.resolve())):
        raise ValueError("Missing or linked mouse sound asset: Sounds/Extras/soft.wav")
    return [(source, Path("sounds/extras/soft.wav"))]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "build" / "website")
    args = parser.parse_args()
    try:
        output = validate_output(args.output)
        site_files = website_files()
        profiles, samples = sound_files()
        mouse_profiles, mouse_samples = sound_files("mouse-profiles.json")
        if {p["id"] for p in profiles}.intersection(p["id"] for p in mouse_profiles):
            raise ValueError("Keyboard and mouse profile IDs must be distinct")
        mouse_samples += mouse_sound_files()
        licenses = license_files()
        output.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix=".clicky-site-", dir=output.parent) as directory:
            staging = Path(directory) / "site"
            staging.mkdir()
            for source, relative in site_files + samples + mouse_samples + licenses:
                destination = staging / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, destination)
            (staging / "profiles.json").write_text(json.dumps(profiles, indent=2) + "\n")
            (staging / "mouse-profiles.json").write_text(json.dumps(mouse_profiles, indent=2) + "\n")
            (staging / ".nojekyll").touch()
            (staging / MARKER).write_text(MARKER_CONTENT)
            # Recheck immediately before replacing a previously generated output.
            validate_output(output)
            if output.exists():
                shutil.rmtree(output)
            staging.rename(output)
        print(f"Prepared {len(profiles)} keyboard profiles, {len(mouse_profiles)} mouse packs, "
              f"{len(samples)} keyboard WAVs and {len(mouse_samples)} mouse WAVs at {output}")
    except (OSError, ValueError, KeyError, TypeError) as error:
        parser.exit(1, f"prepare_website: {error}\n")


if __name__ == "__main__":
    main()
